//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measuring.SmartClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartTransfer_ReceiveEditorView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartTransfer_ReceiveEditorView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measuring.SmartClient.Resources.PartTransfer_ReceiveEditorView", typeof(PartTransfer_ReceiveEditorView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default part.
        /// </summary>
        internal static string DefaultPart {
            get {
                return ResourceManager.GetString("DefaultPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default tare.
        /// </summary>
        internal static string DefaultTare {
            get {
                return ResourceManager.GetString("DefaultTare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Records Editor [{0}].
        /// </summary>
        internal static string DISPLAY_HEADER {
            get {
                return ResourceManager.GetString("DISPLAY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doc. Status.
        /// </summary>
        internal static string DocStatus {
            get {
                return ResourceManager.GetString("DocStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From location.
        /// </summary>
        internal static string FromLocation {
            get {
                return ResourceManager.GetString("FromLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross weight.
        /// </summary>
        internal static string Gross {
            get {
                return ResourceManager.GetString("Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of inventory location.
        /// </summary>
        internal static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind of inventory location.
        /// </summary>
        internal static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot no.
        /// </summary>
        internal static string LotNo {
            get {
                return ResourceManager.GetString("LotNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net weight.
        /// </summary>
        internal static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document no..
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string PartBarcode {
            get {
                return ResourceManager.GetString("PartBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref no..
        /// </summary>
        internal static string ReferenceNo {
            get {
                return ResourceManager.GetString("ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale Status.
        /// </summary>
        internal static string ScaleState {
            get {
                return ResourceManager.GetString("ScaleState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search business-entity.
        /// </summary>
        internal static string SearchBe {
            get {
                return ResourceManager.GetString("SearchBe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search lot of inventory.
        /// </summary>
        internal static string SearchLot {
            get {
                return ResourceManager.GetString("SearchLot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOTAL [Kgs.].
        /// </summary>
        internal static string SummaryHeader {
            get {
                return ResourceManager.GetString("SummaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        internal static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tare weight.
        /// </summary>
        internal static string Tare {
            get {
                return ResourceManager.GetString("Tare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To location.
        /// </summary>
        internal static string ToLocation {
            get {
                return ResourceManager.GetString("ToLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WEIGHT [Kgs].
        /// </summary>
        internal static string WeightLabel {
            get {
                return ResourceManager.GetString("WeightLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KGs..
        /// </summary>
        internal static string WgUnitCode {
            get {
                return ResourceManager.GetString("WgUnitCode", resourceCulture);
            }
        }
    }
}
