//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measuring.SmartClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartTransferItemSearchView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartTransferItemSearchView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measuring.SmartClient.Resources.PartTransferItemSearchView", typeof(PartTransferItemSearchView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil NET WG (kgs.).
        /// </summary>
        internal static string CoilNetWeight {
            get {
                return ResourceManager.GetString("CoilNetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diff weight (kgs.).
        /// </summary>
        internal static string DiffWeight {
            get {
                return ResourceManager.GetString("DiffWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight Detail.
        /// </summary>
        internal static string DISPLAY_HEADER {
            get {
                return ResourceManager.GetString("DISPLAY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GROSS weight (kgs.).
        /// </summary>
        internal static string GrossWeight {
            get {
                return ResourceManager.GetString("GrossWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway type.
        /// </summary>
        internal static string ItemType {
            get {
                return ResourceManager.GetString("ItemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NET weight (kgs.).
        /// </summary>
        internal static string NetWeight {
            get {
                return ResourceManager.GetString("NetWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process sheet not found !.
        /// </summary>
        internal static string NotFound_ProcessSheet {
            get {
                return ResourceManager.GetString("NotFound_ProcessSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string PartCode {
            get {
                return ResourceManager.GetString("PartCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string PartName {
            get {
                return ResourceManager.GetString("PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string PartQty {
            get {
                return ResourceManager.GetString("PartQty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ProductBarcode {
            get {
                return ResourceManager.GetString("ProductBarcode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        internal static string ProductCode {
            get {
                return ResourceManager.GetString("ProductCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ProductName {
            get {
                return ResourceManager.GetString("ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search product.
        /// </summary>
        internal static string SearchProduct {
            get {
                return ResourceManager.GetString("SearchProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq no..
        /// </summary>
        internal static string SeqNo {
            get {
                return ResourceManager.GetString("SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TARE weight (kgs.).
        /// </summary>
        internal static string TareWeight {
            get {
                return ResourceManager.GetString("TareWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio of unit.
        /// </summary>
        internal static string UnitPerRatio {
            get {
                return ResourceManager.GetString("UnitPerRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        internal static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update name with equation barcode.
        /// </summary>
        internal static string UpdateNameSameBarcode {
            get {
                return ResourceManager.GetString("UpdateNameSameBarcode", resourceCulture);
            }
        }
    }
}
