//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measuring.SmartClient.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProcessPlanSearchView {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProcessPlanSearchView() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measuring.SmartClient.Resources.ProcessPlanSearchView", typeof(ProcessPlanSearchView).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil no..
        /// </summary>
        internal static string CoilNo {
            get {
                return ResourceManager.GetString("CoilNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter Coil no..
        /// </summary>
        internal static string CoilNoFilter {
            get {
                return ResourceManager.GetString("CoilNoFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coil Weight (Kgs.).
        /// </summary>
        internal static string CoilWeight {
            get {
                return ResourceManager.GetString("CoilWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process plan item.
        /// </summary>
        internal static string DISPLAY_HEADER {
            get {
                return ResourceManager.GetString("DISPLAY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import File.
        /// </summary>
        internal static string ImportFile {
            get {
                return ResourceManager.GetString("ImportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS no..
        /// </summary>
        internal static string PosNo {
            get {
                return ResourceManager.GetString("PosNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Machine Code.
        /// </summary>
        internal static string ProcessMachineCode {
            get {
                return ResourceManager.GetString("ProcessMachineCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Plan Date.
        /// </summary>
        internal static string ProcessPlanDate {
            get {
                return ResourceManager.GetString("ProcessPlanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Year.
        /// </summary>
        internal static string ProcessYear {
            get {
                return ResourceManager.GetString("ProcessYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remark.
        /// </summary>
        internal static string Remark {
            get {
                return ResourceManager.GetString("Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq no..
        /// </summary>
        internal static string SeqNo {
            get {
                return ResourceManager.GetString("SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start auto import.
        /// </summary>
        internal static string StartAutoImport {
            get {
                return ResourceManager.GetString("StartAutoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop auto import.
        /// </summary>
        internal static string StopAutoImport {
            get {
                return ResourceManager.GetString("StopAutoImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Used.
        /// </summary>
        internal static string Used {
            get {
                return ResourceManager.GetString("Used", resourceCulture);
            }
        }
    }
}
