//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Measurement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Measurement.Resources.EnumMessages", typeof(EnumMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human.
        /// </summary>
        internal static string GatewayItemType_Human {
            get {
                return ResourceManager.GetString("GatewayItemType_Human", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string GatewayItemType_Machine {
            get {
                return ResourceManager.GetString("GatewayItemType_Machine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receive.
        /// </summary>
        internal static string MeasuringMoveType_Into {
            get {
                return ResourceManager.GetString("MeasuringMoveType_Into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issue.
        /// </summary>
        internal static string MeasuringMoveType_Out {
            get {
                return ResourceManager.GetString("MeasuringMoveType_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        internal static string MeasuringMoveType_Records {
            get {
                return ResourceManager.GetString("MeasuringMoveType_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        internal static string MeasuringMoveType_Transform {
            get {
                return ResourceManager.GetString("MeasuringMoveType_Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        internal static string MeasuringStatus_Cancelled {
            get {
                return ResourceManager.GetString("MeasuringStatus_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit.
        /// </summary>
        internal static string MeasuringStatus_Commit {
            get {
                return ResourceManager.GetString("MeasuringStatus_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        internal static string MeasuringStatus_Draft {
            get {
                return ResourceManager.GetString("MeasuringStatus_Draft", resourceCulture);
            }
        }
    }
}
