//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cet.SmartClient.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cet.SmartClient.Client.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string ADD_BUTTON {
            get {
                return ResourceManager.GetString("ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CANCEL_BUTTON {
            get {
                return ResourceManager.GetString("CANCEL_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Doc..
        /// </summary>
        public static string CANCEL_FLOW_BUTTON {
            get {
                return ResourceManager.GetString("CANCEL_FLOW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Doc..
        /// </summary>
        public static string COMMIT_FLOW_BUTTON {
            get {
                return ResourceManager.GetString("COMMIT_FLOW_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EDIT_BUTTON {
            get {
                return ResourceManager.GetString("EDIT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string EMPTY_CODE {
            get {
                return ResourceManager.GetString("EMPTY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Master_Active {
            get {
                return ResourceManager.GetString("Master_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string Master_InActive {
            get {
                return ResourceManager.GetString("Master_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string MODE_NEW {
            get {
                return ResourceManager.GetString("MODE_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MSG_AREYOUSURE {
            get {
                return ResourceManager.GetString("MSG_AREYOUSURE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document has not been saved. Are you sure?.
        /// </summary>
        public static string MSG_CONFIRM {
            get {
                return ResourceManager.GetString("MSG_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string MSG_CONFIRM_CAPTION {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MSG_ERROR_CAPTION {
            get {
                return ResourceManager.GetString("MSG_ERROR_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permission denied..
        /// </summary>
        public static string MSG_PERMISSION_DENIED {
            get {
                return ResourceManager.GetString("MSG_PERMISSION_DENIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknow server error. Check application log file..
        /// </summary>
        public static string MSG_UNKNOW_SERVER_ERROR {
            get {
                return ResourceManager.GetString("MSG_UNKNOW_SERVER_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MSG_WARNING_CAPTION {
            get {
                return ResourceManager.GetString("MSG_WARNING_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK_BUTTON {
            get {
                return ResourceManager.GetString("OK_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Doc..
        /// </summary>
        public static string PRINT_BUTTON {
            get {
                return ResourceManager.GetString("PRINT_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        public static string RELOAD_BUTTON {
            get {
                return ResourceManager.GetString("RELOAD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string REMOVE_BUTTON {
            get {
                return ResourceManager.GetString("REMOVE_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rollback Doc..
        /// </summary>
        public static string ROLLBACK_FLOW_BUTTON {
            get {
                return ResourceManager.GetString("ROLLBACK_FLOW_BUTTON", resourceCulture);
            }
        }
    }
}
